name: Weekly Web Scraper

on:
  schedule:
    # Runs at 3 PM Berlin time (1 PM UTC) every Wednesday
    - cron: '0 13 * * 3'
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Create package.json if it doesn't exist
      run: |
        if [ ! -f package.json ]; then
          echo '{"name": "kino", "version": "1.0.0", "dependencies": {"puppeteer": "^23.4.1"}}' > package.json
        fi

    - name: Install dependencies
      run: npm install

    - name: Run web scraper
      run: node scraper.js

    - name: Commit and push if it changed
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add movie_data.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update movie_data.json" && git push)
